# Remember to update the version in configure.ac and in_adlib.rc
version: 1.9-beta{build}

before_build:
- ps: >-
    # This is the version header to create.

    $file = "src\version.h"


    # Get the ".in" version of the file, replace "@VERSION@" with the Appveyor version number, then save to the target file.

    cat ($file + ".in") | % { $_ -replace "@VERSION@", $env:appveyor_build_version } > $file


build_script:
- cmd: >-
    "%VS140COMNTOOLS%\VsMSBuildCmd.bat"

    appveyor-retry nuget restore contrib\vs2015\vs2015.sln
    
    appveyor-retry nuget update contrib\vs2015\vs2015.sln
    
    FOR %%T IN (v140,v120_xp) DO ( FOR %%C IN (Debug,Release) DO ( echo *** Building %%T/x86/%%C *** && msbuild contrib\vs2015\in_adlib\in_adlib.vcxproj /p:Configuration=%%C /p:Platform=x86 /p:PlatformToolset=%%T /p:SolutionDir=..\ /v:minimal /nologo || EXIT 1 ) )

artifacts:
- path: contrib\vs2015\v120_xp\Win32\Debug\in_adlib.dll
  name: Debug 32-bit

- path: contrib\vs2015\v120_xp\Win32\Release\in_adlib.dll
  name: Release 32-bit

deploy:
- provider: GitHub
  release: ci
  description: 'Latest git build ($(APPVEYOR_BUILD_VERSION))'
  auth_token:
    secure: GF8U8TSB1M3go7zoz3tqlAppk/sjKEhTiB+Zdr8OU7inbPogDQlsQgFmUhRxqblO
  artifact: contrib\vs2015\v120_xp\Win32\Release\in_adlib.dll
  prerelease: true
  force_update: true
  on:
    branch: master

- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'AdPlug Winamp plugin $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: GF8U8TSB1M3go7zoz3tqlAppk/sjKEhTiB+Zdr8OU7inbPogDQlsQgFmUhRxqblO
  artifact: contrib\vs2015\v120_xp\Win32\Release\in_adlib.dll
  on:
    appveyor_repo_tag: true
